// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK6U4H7Vy4krIcDJfuRH01YPo62PWI8w4',
    appId: '1:965203031678:web:6e746db93710dccd7b0a2f',
    messagingSenderId: '965203031678',
    projectId: 'education-app-95660',
    authDomain: 'education-app-95660.firebaseapp.com',
    storageBucket: 'education-app-95660.appspot.com',
    measurementId: 'G-BSH1194RXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjuxj-jnsxIOQX6QR_HtNe5294RXR60ac',
    appId: '1:965203031678:android:bad75f818d3ce1807b0a2f',
    messagingSenderId: '965203031678',
    projectId: 'education-app-95660',
    storageBucket: 'education-app-95660.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGmKNubqjyjONvn_RqmvmUsFmH6pDie1k',
    appId: '1:965203031678:ios:e8710da9778d59617b0a2f',
    messagingSenderId: '965203031678',
    projectId: 'education-app-95660',
    storageBucket: 'education-app-95660.appspot.com',
    iosBundleId: 'com.example.gloukoma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGmKNubqjyjONvn_RqmvmUsFmH6pDie1k',
    appId: '1:965203031678:ios:e8710da9778d59617b0a2f',
    messagingSenderId: '965203031678',
    projectId: 'education-app-95660',
    storageBucket: 'education-app-95660.appspot.com',
    iosBundleId: 'com.example.gloukoma',
  );
}
